version: '3.4'

services:
  adminservice:
    image: bhardwajakash/adminservice:1
    ports:
        - "9877:80"
    container_name: adminservice
    depends_on:
        - consul
        - rabbitmq
        - jaeger-allinone
    links:
        - consul
        - rabbitmq
        - jaeger-allinone

  consumerservice:
    image: bhardwajakash/consumerservice:1
    ports:
        - "9879:80"
    container_name: consumerservice
    depends_on:
        - consul
        - jaeger-allinone
    links:
        - consul
        - jaeger-allinone

  providerservice:
    image: bhardwajakash/providerservice:1
    ports:
        - "9880:80"
    container_name: providerservice
    depends_on:
        - consul
        - jaeger-allinone
    links:
        - consul
        - jaeger-allinone


  ondemandservice:
    image: bhardwajakash/ondemandservice:1
    ports:
        - "9881:80"
    container_name: ondemandservice
    depends_on:
        - consul
        - jaeger-allinone
    links:
        - consul
        - jaeger-allinone

  ordermanagementservice:
    image: bhardwajakash/ordermanagementservice:1
    ports:
        - "9882:80"
    container_name: ordermanagementservice
    depends_on:
        - consul
        - rabbitmq
        - jaeger-allinone
        - paymentservice
        - ondemandservice
        - consumerservice
    links:
        - consul
        - rabbitmq
        - jaeger-allinone
        - paymentservice
        - ondemandservice
        - consumerservice

  notificationservice:
    image: bhardwajakash/notificationservice:1
    ports:
        - "9883:80"
    container_name: notificationservice
    depends_on:
        - consul
        - rabbitmq
        - jaeger-allinone
    links:
        - consul
        - rabbitmq
        - jaeger-allinone

  paymentservice:
    image: bhardwajakash/paymentservice:1
    ports:
        - "9884:80"
    container_name: paymentservice
    depends_on:
        - consul
        - jaeger-allinone
    links:
        - consul
        - jaeger-allinone

  apigateway:
    image: bhardwajakash/apigateway:1
    ports:
        - "9878:80"
    container_name: apigateway
    depends_on:
        - consul
        - jaeger-allinone
    links:
        - consul
        - jaeger-allinone

   consul:
    container_name: consul
    image: consul:latest
    ports:
        - "8500:8500"
        - "8300:8300"
    volumes:
        - ./config:/config
        - ./_data/consul:/data
    command: agent -server -data-dir=/data -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    hostname: rabbitmq

  jaeger-allinone: 
      container_name: jaeger-allinone
      image: jaegertracing/all-in-one:latest
      environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      ports:
          - 5775:5775/udp
          - 6831:6831/udp
          - 6832:6832/udp
          - 5778:5778
          - 16686:16686
          - 14268:14268


